# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 2.7.0'

gem 'access_token_proxy',
    git: 'https://github.com/simayosi/aad-authphone-reg',
    branch: 'main'
gem 'minitest', '~> 5.20.0'
gem 'msgraph-client'
gem 'rake', '~> 13.0'
gem 'securerandom', '~> 0.3.0'
gem 'sinatra', '~> 3.0'

group :mysql2, optional: true do
  gem 'mysql2', '~> 0.5'
end

group :pg, optional: true do
  gem 'pg', '~> 1.3'
end

gem 'activerecord', '~> 7.0.8', group: %i[mysql2 pg]
