# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.3.0'

gem 'rake'
gem 'sinatra'
gem 'msgraph-client'
gem 'access_token_proxy',
    git: 'https://github.com/ykasap/aad-authphone-reg',
    branch: 'main'

group :mysql2, optional: true do
  gem 'mysql2'
end

group :pg, optional: true do
  gem 'pg'
end

gem 'activerecord', group: %i[mysql2 pg]
